### ISSUE TITLE
Nesting level too deep – recursive dependency error during object comparing

### ISSUE THREAD

**Issue by magicaner** [la-haute-societe/yii2-save-relations-behavior#12]
It happens at afterSave, when it compareing 2 active recrods. 
right there:
https://github.com/la-haute-societe/yii2-save-relations-behavior/blob/master/src/SaveRelationsBehavior.php#L315

the problem described here: http://www.php.net/manual/en/language.oop5.object-comparison.php

can you use === operator here instead of == ?

**Comment by juban** [comment]
Thanks for your report.

**Comment by juban** [comment]
@magicaner Could you provide any use case or example of that issue? Thx.

**Comment by magicaner** [comment]
i am trying to repeat the error, but cant for some reason. not sure how to repeat the error. but i got those errors multiple times. 
here people talking about similar problem:
http://stackoverflow.com/questions/3834791/fatal-error-nesting-level-too-deep-recursive-dependency#answer-19097159

**Comment by magicaner** [comment]
i was able to repeat it. it happens if all following cases are true:
1. previous and new value is not empty
2. related model for old and new value are exists
3. relation type is "hasOne"

**Comment by juban** [comment]
@magicaner Yes, I figured that out already.
But the scenario you are suggesting is not enough to trigger the issue.
There must be some cross-reference relations affecting the behavior.
Don't get me wrong, I'm not saying there is no issue here (I will definitely fix that), but I'm struggling to find a proper model setup to reproduce that.
Could you give me (even partially) your models definitions involved in that issue?
Thank you for your help.

**Comment by juban** [comment]
@magicaner OK, never mind, I found a way to reproduce the issue.
Bug will be fixed in an upcoming release.
Thanks again.

**Comment by juban** [comment]
Fixed with 49cae2c76bfe3c112b275b3c0f25b01a27e489f1
