### ISSUE TITLE
Could it possible to add exception logging into saveRelatedRecords function?

### ISSUE THREAD

**Issue by mythicallage** [la-haute-societe/yii2-save-relations-behavior#17]
Could it possible to add exception logging into saveRelatedRecords function?

If you catch [yii\db\Exception] PDOException, you will not find any information about it.
Further, \yii\db\ActiveRecord->getErrors() will not return any error.

**Comment by juban** [comment]
Yes, you are right, it could totally be useful in a debugging context.
I'm thinking of adding a Yii:warning() log specifying the exception class name and message.
What do you think ?

**Comment by mythicallage** [comment]
In my opinion, it looks pretty good. I don't see any better way to fix it. Thank you so much.

**Comment by juban** [comment]
I have pushed an updated version of the saveRelatedRecords method into the master branch.
Could you test it and let me know if you have any issue?
Thanks.

**Comment by mythicallage** [comment]
Thank you. It was useful to find my mistake.

I was looking for improvements to save related models, but it is not as easy as I wanted. The main problem is that how to define an independent model and save it to avoid double saving attempts. I can't see any hint in \yii\db\BaseActiveRecord::getRelation, \yii\db\BaseActiveRecord::link.

e. g. 
MainActiveRecord hasOne SubordinateActiveRecord.
Primary Key of MainActiveRecord is auto incremented.
I expected an attempt to save SubordinateActiveRecord after BaseActiveRecord::EVENT_AFTER_INSERT or EVENT_AFTER_UPDATE. But we have to run saving it twice for the universality of behavior.

**Comment by juban** [comment]
Upcoming 1.3.0 release will hopefully cover that more gracefully.
Your feedback is appreciated.
