### ISSUE TITLE
Separation of validation and saving does unique validation not possible

### ISSUE THREAD

**Issue by boryashkin** [la-haute-societe/yii2-save-relations-behavior#18]
When i save a model with "hasMany" relation it does validate each of relations from an array and then saving them with `->save(false)`. But i have the unique validation rule in relation model, which shouldn't let it save both of them in this example:

```
ParentModel [
    'property' => 'value',
    'relation' => [
        [
            'name' => 'ex1',
            'uniqueField' => 1,
        ],
        [
            'name' => 'ex2',
            'uniqueField' => 1,//shouldn't be saved
        ],
    ],
]
```

Logs:
------
1. SELECT CASE WHEN EXISTS(SELECT * FROM relation WHERE uniqueField = 1) THEN 1 ELSE 0 END FROM DUAL; /* validation of ex1 */
2. SELECT CASE WHEN EXISTS(SELECT * FROM relation WHERE uniqueField = 1) THEN 1 ELSE 0 END FROM DUAL; /* validation of ex2 */
3. INSERT ... ex1
4. INSERT ... ex2
-----

Instead of SELECT /*ex1*/, INSERT /*ex1*/, SELECT /*ex2*/, addError

**Comment by boryashkin** [comment]
It could be solved by a custom rule for the 'relation' array though

```
[['relation'], function ($attribute) {
    /* ...  */
}],
```

**Comment by juban** [comment]
Hi,

I understand the issue, but the workaround eludes me.
Could you elaborate a bit more please?

Thanks.

**Comment by boryashkin** [comment]
It could be a filter:
```
[['relation'], 'filter', 'filter' => function ($value) {
    /* simplified example  */
    return array_unique($value);
}],
```
or a validator:

```
[['relation'], function ($attribute) {
    /* simplified example  */
    $rels = [];
    foreach ($this->$attribute as $key => $value) {
        if ($key != 'uniqueField') {
            continue;
        }
        if (isset($rels[$value])) {
            $this->addError($attribute, '"uniqueField" of "relation" must be unique')
        } else {
            $rels[$value] => true;
        }
    }
}],
```

It may even be better than going to a DB for a constraint error

**Comment by juban** [comment]
In the upcoming 1.3.0 release due shortly, related models will be also validated during the `afterSave` event. If any validation occurs (or database related error), a `yii\db\Exception` will be thrown and an error message will be attached to the relation attribute of the owner model. A rollback will automatically be applied in that case (if relevant). Also, the behavior will log a warning in these circumstances.
Hope it will help in the case you mentioned.

Anyway, your suggestion is a great way to workaround the validation issue for key uniqueness.
Thanks.
