### ISSUE TITLE
hasOne Relation before validate event don't fired 

### ISSUE THREAD

**Issue by dabkhazi** [la-haute-societe/yii2-save-relations-behavior#24]
Hello! 
Thank you for your work!

I found a little issue. If i defined relation as hasOne, then child relation don't fire before validate event. Change relation to hasMany and all is ok.

**Comment by juban** [comment]
Thank you for reporting.
I'll take a look as soon as possible.

**Comment by juban** [comment]
Fixed in 1.4.1 release.
