### ISSUE TITLE
Many-to-many relation stopped working after updating Yii2 to 2.0.14

### ISSUE THREAD

**Issue by alexanderYakovenkoUkr** [la-haute-societe/yii2-save-relations-behavior#25]
After updating Yii2 to 2.0.14 my Many-to-many relation stopped working.
I returned my yii2 to 2.0.13.1 (as I used to work before), and relation continued to work.

**Comment by juban** [comment]
Active Record relations have been updated in a significant manner in the 2.0.14 release and could have some sides effects on the behavior.
I will take a look as soon as possible to hopefully make it work with the new release.

**Comment by juban** [comment]
See http://www.yiiframework.com/news/165/yii-2-0-14-is-released/

**Comment by alexanderYakovenkoUkr** [comment]
Ok :) Thanks for your behavior and so quick response. let me know when it will be possible to upgrade to 2.0.14 and check the operability

**Comment by juban** [comment]
Issue has been fixed. New Active Record mechanism that refresh outdated relations after save as described [here](https://github.com/yiisoft/yii2/issues/14233) prevented the behavior to retrieve the updated values.
