### ISSUE TITLE
updated values of the relations cannot be correctly accessed in the afterSave method of the master model

### ISSUE THREAD

**Issue by dabkhazi** [la-haute-societe/yii2-save-relations-behavior#26]
Hello! 
I don't know exactly is this a bug or not but will try explain my problem. 
Suppose we have Orders and OrderItems. 

Orders:

class Order ... { 

 ....

public function behaviors()
    {
        return [
			.....
            [
                'class' => SaveRelationsBehavior::class,
                'relations' => [
                    'orderItems'
                ]
            ],
			.....
        ];
 }

public function getOrderItems()
{
        return $this->hasMany(OrderItem::class, ['order_id' => 'order_id']);
}

public function afterSave($insert, $changedAttributes)
{
      var_dump(count($this->orderItems));  die();
      retrun parent::afterSave($insert, $changedAttributes);
}

....

}

$order = new Order();
$order->orderItems = OrderItem[]; // simplified code
$order->save();

after that i see that afterSave method: count($this->orderItems) = 0.

but 

$order = Order::findOne(1);
$order->orderItems = OrderItem[]; // simplified code
$order->save();

after that i see that afterSave: count($this->orderItems) > 0.

When i insert a new Order, before insert OrderItems i want to modify them. I can modify only when updating the Order, not when inserting.

**Comment by juban** [comment]
Could you specify the Yii2 Framework version you are using please?

**Comment by juban** [comment]
I guess you are using Yii 2.0.14 or later.
Be aware that with this version, Yii is resetting relations after it saves the master record.
The behavior is saving the relations during the afterSave event which is triggered after the afterSave method of the master model. Due to current limitations, that's why you don't get the right count.
I will try to find a way to access the correct relations values.

Thanks for reporting.

**Comment by juban** [comment]
@dabkhazi Forget what I said. I did a couple of tests and could not reproduce your issue. 
Are you using the latest version of this behavior? 
If you are using it with Yii 2.0.14 or later, please upgrade to version 1.4.0 or later. Thanks.

**Comment by dabkhazi** [comment]
I am using yii 2.0.14.1 and 1.4.1 behavior

пн, 12 марта 2018 г., 20:22 Alban Jubert <notifications@github.com>:

**Comment by juban** [comment]
Ok. Could you try to provide some test case please?
For instance, the way you set the orderItems relation. 
Thx.

**Comment by dabkhazi** [comment]
I found the reason of that. My test Order class has method addItems:

    public function addItems(array $items)
    {
        $this->orderItems = array_merge($this->orderItems,$items);
    }  

I fixed my problem, added this code before invoke above method:
$order->orderItems = [];
$order->addItems(OrderItem[]);  // simplified code

but can't understand why this helped

**Comment by juban** [comment]
@dabkhazi 
Glad to know you found a workaround.
And thank you for using this behavior :)
