### ISSUE TITLE
attributeBehavior for primarykey reset populated hasmany relations

### ISSUE THREAD

**Issue by DaveFerger** [la-haute-societe/yii2-save-relations-behavior#27]
i have a UniquIdBehavior for id (primary key)

this reset populated relations, after https://github.com/yiisoft/yii2/pull/13618 pr merged:

```php
public function __set($name, $value)
    {
        if ($this->hasAttribute($name)) {
            if (
                !empty($this->_relationsDependencies[$name])
                && (!array_key_exists($name, $this->_attributes) || $this->_attributes[$name] !== $value)
            ) {
                $this->resetDependentRelations($name);
            }
            $this->_attributes[$name] = $value;
        } else {
            parent::__set($name, $value);
        }
    }
```

**Comment by juban** [comment]
Hi,

Thank you for your report but could you elaborate a bit?
Are you referring to issue #25 ?
If so, you should upgrade to the latest version of the behavior in order to work with Yii2 2.0.14 and later. 
If not, could you give a use case scenario where that’s not working?

Thanks.

**Comment by juban** [comment]
I'm closing this issue.
Feel free to reopen it if have additional informations.
Thanks.
