### ISSUE TITLE
Delete relation on array field postgresql

### ISSUE THREAD

**Issue by ghost** [la-haute-societe/yii2-save-relations-behavior#28]
I have array field with ids of 3 related items and hasMany relation. Then I delete one of them and
when I try to save the model it is deleted. I think the problem is in the method $model->unlink($relationName, $initialModels[$key], true). Since there is no via table and a parameter $delete is true it deletes the parent model.

**Comment by juban** [comment]
Hi @omnicore01,

Well, if your related data is directly linked to your master model (ie. not linked in a "many to many" way), that's the intended result.
Why would you want to keep an orphan record with no master record linked to it?
Could you elaborate a bit more on you specific use case?

Thanks.
