### ISSUE TITLE
Strange behavior saving newly created hasOne entity

### ISSUE THREAD

**Issue by phrakon** [la-haute-societe/yii2-save-relations-behavior#30]
I have a Profile Model. The model saved into database and has an ID. It has relation 
public function getPerson()
    {
        return $this->hasOne(Person::className(), ['user_id' => 'user_id']);
    }
Both user_id are primary key (One to One). But no person record exists.
Of course a have no
<?php echo $form->field($model, 'person[user_id]')->hiddenInput(); ?>
line in the view file

Then i save the Profile. It throws an constrait error. https://github.com/la-haute-societe/yii2-save-relations-behavior/blob/953e976e4baaf0e868d92727484b32a093763e65/src/SaveRelationsBehavior.php#L239 sets primary key of Profile model to null because $model->{$modelAttribute} !== $model->{$relationName}->{$relatedAttribute} where $model->{$relationName}->{$relatedAttribute} is null

It happens because Person model has not been saved because https://github.com/la-haute-societe/yii2-save-relations-behavior/blob/953e976e4baaf0e868d92727484b32a093763e65/src/SaveRelationsBehavior.php#L579 Line return false because $p2 is primary key. And person model has been validated only. Why are so difficult conditions (i am not allowed to have both as pk)?

https://github.com/la-haute-societe/yii2-save-relations-behavior/issues/29 has a similar issue. Possibly we don't unserstand how to manipulate hasOne relations..

https://github.com/la-haute-societe/yii2-save-relations-behavior/blob/953e976e4baaf0e868d92727484b32a093763e65/src/SaveRelationsBehavior.php#L237 writes me "Setting foreign keys for person" but https://github.com/la-haute-societe/yii2-save-relations-behavior/blob/953e976e4baaf0e868d92727484b32a093763e65/src/SaveRelationsBehavior.php#L240 sets Profile property to null in my case.

**Comment by phrakon** [comment]
[tt.zip](https://github.com/la-haute-societe/yii2-save-relations-behavior/files/2217210/tt.zip)

**Comment by juban** [comment]
@phrakon Thank you for the detailed report.
I'm working on it.
That will be fixed in the upcoming release.

**Comment by juban** [comment]
@phrakon That should be fixed now. Thx.

**Comment by juban** [comment]
Hi, I reopen that issue as the fix in 1.5.0 introduced a serious regression.
