### ISSUE TITLE
Validation trouble

### ISSUE THREAD

**Issue by phrakon** [la-haute-societe/yii2-save-relations-behavior#32]
if i use input form like
```
<?= $form->field($user, 'profile[opf_id]')->dropDownList(Opf::getDropDown(), ['prompt' => ''])
                        ->label(Profile::instance()->getAttributeLabel('opf_id')); ?>
```

i didn't watch validation errors.

i found out that your method has to be like

```
 private function _addError($relationModel, $owner, $relationName, $prettyRelationName)
    {
        foreach ($relationModel->errors as $attribute=>$attributeErrors) {
            foreach ($attributeErrors as $error) {
                $owner->addError("{$relationName}[{$attribute}][]", "{$prettyRelationName}: {$error}");
            }
        }
    }
```

it helps to render any error for related inputs.
How is the right way to build form-field statement and validate input data in my case?

**Comment by juban** [comment]
Hi @phrakon,

I'm wondering why don't you use models and the validation errors from the related models directly in your forms?
That way, you will even benefit from the client side validations.

**Comment by juban** [comment]
Hi @phrakon,

Let me clarify my somewhat terse previous comment ;)

In your case, you could do something like:
```php
<?= $form->field($user->profile, 'opf_id')->dropDownList(Opf::getDropDown(), ['prompt' => '']); ?>
```
By doing so, you will get all the validations data directly from the related model including error messages if any (you will just have to deal with setting a new profile model in your view in case the relation is empty).
Error messages affected to the related named attribute on the owner model level is just a mean to invalidate it if a related model has validation errors.
I hope it's clear.
Please, let me know if you need some clarifications.

**Comment by phrakon** [comment]
Let me time to check all the possibilities :).

**Comment by phrakon** [comment]
In your case i have to override ActiveForm::validate() method to perform ajax errors or use ActiveForm::validateMultiple for main and related models. Because the internal _addError method inject an error message to main model only. So, i want to achive the goal that show an error message nearby any input field any related model but not at the end of their list.

**Comment by phrakon** [comment]
I don't know how to implement ajax validation in your case. _addError method inject an error message to main model. I should override ActiveForm::validate or pass all models to it... Have no idea to do that.

**Comment by juban** [comment]
`ActiveForm::validate` accept multiple models as arguments. So you could do something like:
`ActiveForm::validate($model, $model->profile);`. It will populate the response with the according validation messages for each attributes.
