### ISSUE TITLE
Can't set virtual attribute for ActiveRecord

### ISSUE THREAD

**Issue by phrakon** [la-haute-societe/yii2-save-relations-behavior#33]
My ActiveRecord class has the attribute

```
class Profile extends ActiveRecord
{
   /**
     * @var bool
     */
    public $agree;

public function rules()
    {
        return [
         
            [['agree'], 'required', 'on' => 'insert'],
         
        ];
    }
}
```
But i have got an error "Failed to set unsafe attribute 'agree' in 'app\models\user\Profile'."

I found out we have to set scenario here if scenario provided by behavior
https://github.com/la-haute-societe/yii2-save-relations-behavior/blob/5e2fe7925a3670139391f2b143176077befd24a0/src/SaveRelationsBehavior.php#L255

Anyway it helps me to work/ Isn't it the right case?

**Comment by phrakon** [comment]
Update. There is no sense depends on type of the attribute. Scenario should be applied before assigning attributes (after object will be instatiated to be sure in the future) because setAttributes checks safe ability of attributes depends on current scenario. You do it before validate. Its too late.

**Comment by juban** [comment]
Hi @phrakon,

Yep, you’re right. 
Bug fix is on its way. The master branch contains a first fix but there’s still one issue. I will hopefully publish the full fix tomorrow. 

Thanks.
