### ISSUE TITLE
Auto start transactions capability

### ISSUE THREAD

**Issue by juban** [la-haute-societe/yii2-save-relations-behavior#39]
Let the behavior start transactions automatically based on a behavior global property (see #38)

**Comment by leandrogehlen** [comment]
This feature was not implemented.
Can i build the PR for it?

**Comment by juban** [comment]
I'm wondering if that's still relevant as the transaction process is now fully handled natively by the ActiveRecord. I mean, if the transaction method is defined for the master model, it will start the transaction accordingly. I would not want to overload the behavior with a feature that already exists.
