### ISSUE TITLE
Updating multiple records in nested related model

### ISSUE THREAD

**Issue by abhimanusharma** [la-haute-societe/yii2-save-relations-behavior#40]
*Scenario :*

    $scenarios[self::SCENARIO_SAVE_STEP_2] = ['company', 'address', 'vehicles', 'id'];

*Behavior :*
```
    public function behaviors() {
            return [
                'saveRelations' => [
                    'class'     => SaveRelationsBehavior::className(),
                    'relations' => [
                        'company' => ['scenario' => Company::SCENARIO_COMPANY],
                        'address' => ['scenario' => Address::SCENARIO_PROFILE_COMPANY],
                        'vehicles' => ['scenario' => Vehicle::SCENARIO_PROFILE_VEHICLE]
                      ]
                  ],
            ];
    }
```

*example :* In User Model,
```
    $user = User::findOne($this->id);
    $user->scenario = User::SCENARIO_SAVE_STEP_2;
    $user->load(Yii::$app->getRequest()->getBodyParams(), '');
```

*Payloads,*
```
    {
    id:1,
    name : "adam",
        company : {
            id : "2",
            userid : "1",
            name : "My Company",
            logo : {
                id : "1",
                url : "http://myimage.com/logo.png"
                }
        },
        address : {
            id : "1",
            userid : "1",
            name : "My Company",
        },
        vehicles : [
            { 

             id : 2,
             type : "two wheeler"
             licenseImages : [{
                id : "3",
                url : "http://myimage.com/license.png"
                }]

             },

            { 

             id : 3,
             type : "four wheeler"
             licenseImages : [{
                id : "4",
                url : "http://myimage.com/license.png"
                }]

             }

        ]
    }
```
----------------------------------------------------

*This is working:*

    1. New record save for hasOne relation, when primary key is given blank.

    2. New data for Nested relation hasMany, data is saving.

*This is NOT working:*

    1. Existing record update for hasOne relation, when primary key is given.
    2. Existing data for Nested relation hasMany, data is not saving, with primary key given in payload.
    3. New data is not saving for hasMany relation when data is given in array (ref. vehicles in above example).
    4. Existing data is not saving for hasMany relation when data is given in array (ref. vehicles in above example), with primary key i.e id.
    5. New or Existing data for Nested relation hasMany, data is not saving, with primary key given in payload. (ref. vehicles->licenseImages in above example)

 
 My system configuration :
Yii2 = Version 2.0.14
PHP = Version 7.1.20
Mysql Server = Version 5.7.23
Extenstion = Version ^1.5

**Comment by juban** [comment]
Hi @dragonabv,

Thank you for the report. For now, the behavior have limited support for nested relations (see #23). Anyway, I will try to take a look at your use case as soon as I can. Thanks.

**Comment by abhimanusharma** [comment]
Hi @juban ,

I have already saw those test cases. They are not working as they should. Hope you will fix the bug and update it in next release. Thanks.

**Comment by juban** [comment]
Hi @dragonabv,
I think lastest fix will work as intended in your use case.
Please, feel free to reopen that issue if that's not the case.
