### ISSUE TITLE
usage question maybe a bug?

### ISSUE THREAD

**Issue by papppeter** [la-haute-societe/yii2-save-relations-behavior#49]
hi,

i just cannot find out how this is working. i did put it in my project, did set up as an document, but it is just not working. i did recognised some parts which could be buggy, but of course if it works for everyone else, than the problem will be with me.

if i add new line here :

protected function _setRelationForeignKeys($relationName)
    {
        /** @var BaseActiveRecord $owner */
        $owner = $this->owner;
        /** @var ActiveQuery $relation */
        $relation = $owner->getRelation($relationName);
        if ($relation->multiple === false && !empty($owner->{$relationName})) {
            Yii::debug("Setting foreign keys for {$relationName}", __METHOD__);
            foreach ($relation->link as $relatedAttribute => $modelAttribute) {
                if ($owner->{$modelAttribute} !== $owner->{$relationName}->{$relatedAttribute}) {
                    if ($owner->{$relationName}->isNewRecord) {
                        **$owner->{$relationName}->{$relatedAttribute} = $owner->{$modelAttribute};**
                        $owner->{$relationName}->save();
                    }
                    $owner->{$modelAttribute} = $owner->{$relationName}->{$relatedAttribute};
                }
            }
        }
    }

than it starts working for me as well. i just could not find out where will be set all the foreign keys.

the another one is:
_prepareHasOneRelation
in my mind this one is wrong: 
        $p1 = $model->isPrimaryKey(array_keys($relation->link));
        $p2 = $relationModel::isPrimaryKey(array_values($relation->link));
the first one should be array_values, second array_keys. but maybe i don't understand the porpuse of the method.

my setup is really strait forward:

            'saveRelations' => [
                'class' => SaveRelationsBehavior::class,
                'relations' => [
                    'personDetail',
                    'personAddress',
                    'personEmails',
                    'personPhones',
                    'personSocials',
                    'user',
                ],
            ]

but it cannot handle new records, it deals perfect with existing ones. My db should be ok, gii can generate model properly.

**Comment by papppeter** [comment]
if i see it right:

                        if ($relation->multiple === false) {
                            $this->_prepareHasOneRelation($model, $relationName, $event);
                        } else {
                            $this->_prepareHasManyRelation($model, $relationName);
                        }

this two method should add the fks to the related models. but _prepareHasManyRelation does not contain anything related this, only a validation which fails.

**Comment by papppeter** [comment]
Hi,

this was my fault. we created some short cuts for hasMany relation to get first record -> hasOne . and of course it was not working.

my only question is now, if a fk is required rule sets it required can this widget handle it? or required should be removed?

**Comment by juban** [comment]
Hi,

As stated in the extension documentation:

`For relations not involving a junction table by using the via() or viaTable() methods, you should remove the attributes pointing to the owner model from the 'required' validation rules to be able to pass the validations.`

So basically, yes, it should be removed prior to model saving.

Feel free to reopen the issue if you have other questions in order to pass model validation.

Thanks.
